name: Trivy Image Vulnerability Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: #RUCHNOY ZAPUSK

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb

      - name: Scan image for High vulnerabilities
        run: trivy image --severity HIGH --exit-code 1 alpine/openssl:latest
